" =====================================================
"
"      Author:   	Jorge Castano  
"
" =====================================================


"------------------- GENERAL -------------------

let mapleader = "\<Space>"

" Remap VIM 0 to first non-blank character
nmap 0 ^


" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk


" Paste at the end of line leaving one space 
" nnoremap [it was 1 but i need to replace to <leader> something otherwise i cannot do 15G to go to line 15 ] A <C-r>"<esc>


" Escape from insert mode with combination of keys jk or kj
imap jk <esc>
imap kj <esc>


" Quickly insert an empty new line without entering insert mode
    nnoremap <Leader>o o<Esc>
    nnoremap <Leader>O O<Esc>

" Always show current position (row & column)
set ruler		


" Show command-keys pressed on bottom-right
set showcmd		


" Ignores case when searching and do incremental searching
set ignorecase
set incsearch       


" Display relative line numbers, with absolute line number for current line
set relativenumber 
set number 
set numberwidth=5

" Don't require saving before closing a buffer
set hidden
